server:
  port: 8081

spring:
  datasource:
    #mysql的配置加载驱动类信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql的连接信息
    url: jdbc:mysql://localhost:3306/zhikao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone = GMT
    #用户名
    username: root
    #密码
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.server.pojo
  configuration:
    map-underscore-to-camel-case: false


logging:
  level:
    com.xxxx.server.mapper: debug


